import { supabase } from './supabase';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

async function authHeaders() {
  const { data: { session } } = await supabase.auth.getSession();
  if (!session?.access_token) return {};
  return { Authorization: `Bearer ${session.access_token}` };
}

/**
 * Generate a tailored cover letter for a given analysis.
 */
export async function generateCoverLetter(analysisId, { regenerate = false } = {}) {
  const headers = await authHeaders();
  const res = await fetch(`${API_URL}/generate-cover-letter`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...headers },
    body: JSON.stringify({
      analysis_id: analysisId,
      regenerate,
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.detail || 'Failed to generate cover letter');
  }
  return res.json();
}

/**
 * Download a cover letter as a .docx file.
 * Follows the same pattern as downloadResumeAsDocx.
 */
export async function downloadCoverLetterAsDocx(text, roleName = '', companyName = '', onError) {
  let Document, Packer, Paragraph, TextRun, AlignmentType, saveAs;
  try {
    ({ Document, Packer, Paragraph, TextRun, AlignmentType } = await import('docx'));
    ({ saveAs } = await import('file-saver'));
  } catch {
    if (onError) onError('Download failed — try again');
    return;
  }

  try {
    const children = [];
    const today = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    // Subtle Holt branding header
    children.push(new Paragraph({
      alignment: AlignmentType.RIGHT,
      children: [
        new TextRun({
          text: 'Generated by Holt',
          size: 16,
          color: '999999',
          italics: true,
          font: 'Calibri',
        }),
      ],
      spacing: { after: 400 },
    }));

    // Company + role header
    if (companyName || roleName) {
      children.push(new Paragraph({
        children: [
          new TextRun({
            text: [companyName, roleName].filter(Boolean).join(' — '),
            bold: true,
            size: 24,
            font: 'Calibri',
            color: '1E8F99',
          }),
        ],
        spacing: { after: 80 },
      }));
    }

    // Date
    children.push(new Paragraph({
      children: [
        new TextRun({
          text: today,
          size: 21,
          font: 'Calibri',
          color: '666666',
        }),
      ],
      spacing: { after: 400 },
    }));

    // Body paragraphs
    const paragraphs = text.split(/\n\n+/).filter((p) => p.trim());
    for (const para of paragraphs) {
      children.push(new Paragraph({
        children: [
          new TextRun({
            text: para.trim(),
            size: 22,
            font: 'Calibri',
          }),
        ],
        spacing: { after: 200, line: 360 },
      }));
    }

    // Signature
    children.push(new Paragraph({ spacing: { before: 200 } }));
    children.push(new Paragraph({
      children: [
        new TextRun({
          text: 'Sincerely,',
          size: 22,
          font: 'Calibri',
        }),
      ],
      spacing: { after: 100 },
    }));

    // Try to extract name from the cover letter text (first "I" reference or sign-off)
    const nameMatch = text.match(/^(.+),?\s*$/m);
    const sigName = nameMatch?.[1]?.match(/[A-Z][a-z]+ [A-Z][a-z]+/)?.[0] || '';
    if (sigName) {
      children.push(new Paragraph({
        children: [
          new TextRun({
            text: sigName,
            size: 22,
            font: 'Calibri',
            bold: true,
          }),
        ],
      }));
    }

    const doc = new Document({
      sections: [{
        properties: {
          page: {
            margin: { top: 1080, bottom: 1080, left: 1080, right: 1080 },
          },
        },
        children,
      }],
    });

    const blob = await Packer.toBlob(doc);
    const fileName = [roleName, companyName, 'Cover_Letter']
      .filter(Boolean)
      .join('_')
      .replace(/\s+/g, '_')
      + '.docx';
    saveAs(blob, fileName);
  } catch {
    if (onError) onError('Download failed — try again');
  }
}
