import { supabase } from './supabase';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

async function authHeaders() {
  const { data: { session } } = await supabase.auth.getSession();
  if (!session?.access_token) return {};
  return { Authorization: `Bearer ${session.access_token}` };
}

/**
 * Generate an ATS-optimized resume for a given analysis.
 */
export async function generateResume(analysisId, linkedinText = '') {
  const headers = await authHeaders();
  const res = await fetch(`${API_URL}/generate-resume`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...headers },
    body: JSON.stringify({
      analysis_id: analysisId,
      linkedin_text: linkedinText,
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.detail || 'Failed to generate resume');
  }
  return res.json();
}

/**
 * Retrieve a previously generated resume.
 */
export async function getGeneratedResume(analysisId) {
  const headers = await authHeaders();
  const res = await fetch(`${API_URL}/generate-resume/${analysisId}`, { headers });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.detail || 'Failed to load generated resume');
  }
  return res.json();
}

/**
 * Simple markdown to structured sections parser for display.
 */
export function parseResumeMarkdown(md) {
  if (!md) return [];

  const sections = [];
  const lines = md.split('\n');
  let currentSection = null;

  for (const line of lines) {
    const h1 = line.match(/^# (.+)/);
    const h2 = line.match(/^## (.+)/);
    const h3 = line.match(/^### (.+)/);
    const bullet = line.match(/^[-*] (.+)/);

    if (h1) {
      currentSection = { type: 'name', title: h1[1], content: [] };
      sections.push(currentSection);
    } else if (h2) {
      currentSection = { type: 'section', title: h2[1], content: [] };
      sections.push(currentSection);
    } else if (h3) {
      currentSection = { type: 'subsection', title: h3[1], content: [] };
      sections.push(currentSection);
    } else if (bullet && currentSection) {
      currentSection.content.push(bullet[1]);
    } else if (line.trim() && currentSection) {
      currentSection.content.push(line.trim());
    }
  }

  return sections;
}

/**
 * Convert markdown resume to a .docx file and trigger download.
 * Dynamically imports docx + file-saver to avoid loading them on page load.
 */
export async function downloadResumeAsDocx(md, roleName = '', companyName = '') {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = await import('docx');
  const { saveAs } = await import('file-saver');

  const sections = parseResumeMarkdown(md);
  const children = [];

  // Subtle Holt branding header
  children.push(new Paragraph({
    alignment: AlignmentType.RIGHT,
    children: [
      new TextRun({
        text: 'Generated by Holt',
        size: 16,
        color: '999999',
        italics: true,
        font: 'Calibri',
      }),
    ],
    spacing: { after: 200 },
  }));

  for (const section of sections) {
    if (section.type === 'name') {
      children.push(new Paragraph({
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({
            text: section.title,
            bold: true,
            size: 36,
            font: 'Calibri',
          }),
        ],
        spacing: { after: 200 },
      }));
      // Any content under the name (contact info, etc.)
      for (const line of section.content) {
        children.push(new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [
            new TextRun({ text: line, size: 20, font: 'Calibri' }),
          ],
        }));
      }
    } else if (section.type === 'section') {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [
          new TextRun({
            text: section.title.toUpperCase(),
            bold: true,
            size: 24,
            font: 'Calibri',
            color: '1E8F99',
          }),
        ],
        spacing: { before: 300, after: 100 },
        border: {
          bottom: { color: '1E8F99', space: 1, style: 'single', size: 6 },
        },
      }));
      for (const line of section.content) {
        children.push(new Paragraph({
          children: [
            new TextRun({ text: line, size: 21, font: 'Calibri' }),
          ],
          spacing: { after: 80 },
        }));
      }
    } else if (section.type === 'subsection') {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [
          new TextRun({
            text: section.title,
            bold: true,
            size: 22,
            font: 'Calibri',
          }),
        ],
        spacing: { before: 200, after: 60 },
      }));
      for (const line of section.content) {
        children.push(new Paragraph({
          bullet: { level: 0 },
          children: [
            new TextRun({ text: line, size: 21, font: 'Calibri' }),
          ],
          spacing: { after: 40 },
        }));
      }
    }
  }

  const doc = new Document({
    sections: [{
      properties: {
        page: {
          margin: { top: 720, bottom: 720, left: 720, right: 720 },
        },
      },
      children,
    }],
  });

  const blob = await Packer.toBlob(doc);
  const fileName = [roleName, companyName, 'Resume']
    .filter(Boolean)
    .join('_')
    .replace(/\s+/g, '_')
    + '.docx';
  saveAs(blob, fileName);
}
